# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('alive', models.BooleanField()),
                ('http_code', models.IntegerField()),
                ('pdf_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.PdfFiles')),
            ],
        ),
    ]
